#!/bin/bash

redx="\e[1;31m"
ncx="\e[0m" # No color
boldx="\033[1m

# Check if the script is being run as root
if [[ $EUID -ne 0 ]]; then
    echo "${redx}This script must be run as root, login to root shell or it will break pkg. Exiting.${ncx}"
    exit 1
fi

mkdir /home/$USER/wazuh-all
cd /home/$USER/wazuh-all 

clear
echo -e "\e[1;31m_______________________________________________\e[0m" #red
echo ""
echo -e "\e[7;1;5;31m Increase max_map_count on your Docker host\e[0m"
echo -e "\e[1;31m_______________________________________________\e[0m
sleep 0.5
sysctl -w vm.max_map_count=262144
clear

echo "${boldx}--------------------------${ncx}"
echo "${boldx} Start the Docker service ${ncx}"
echo "${boldx}--------------------------${ncx}"
systemctl start docker

echo "${boldx}---------------------------------------${ncx}"
echo "${boldx} Changing Docker User-Group Permission ${ncx}"
echo "${boldx}---------------------------------------${ncx}"
sleep 1
usermod -aG docker
clear
echo "${boldx}----------------------------${ncx}"
echo "${boldx} Downloading Docker compose ${ncx}"
echo "${boldx}----------------------------${ncx}"
sleep 1
curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /root/docker-compose
clear
echo "${boldx}---------------------${ncx}"
echo "${boldx} Changing Permission ${ncx}"
echo "${boldx}---------------------${ncx}"
chmod +x /root/docker-compose
sleep 1
clear

mv /root/docker-compose /usr/local/bin/

git clone https://github.com/wazuh/wazuh-docker.git -b v4.9.2

read -p "Would you like Single or Multi (S/M): " nodex

# Convert input to lowercase for case-insensitivity
nodex=$(echo "$nodex" | tr '[:upper:]' '[:lower:]')

if [[ "$nodex" == "s" ]]; then
    cd  /home/$USER/wazuh-all/wazuh-docker/single-node || exit
    docker-compose -f generate-indexer-certs.yml run --rm generator
    docker-compose up -d
    echo "All done! Single Node has been deployed." | lolcat

elif [[ "$nodex" == "m" ]]; then
    cd  /home/$USER/wazuh-all/wazuh-docker/multi-node || exit
    docker-compose -f generate-indexer-certs.yml run --rm generator
    docker-compose up -d
    echo "All done! Multi Node has been deployed." | lolcat

else
    echo "Wrong option. Please choose 'S' for Single or 'M' for Multi."
fi
